[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
fs_permissions = [{ access = "read", path = "./" }]
optimizer = true
optimizer_runs = 2_000

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
